<?php
/**
 *  * @author Eng.Asma Hawari
 *  * @package VexSolutions_LoginCustomization
 */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">

    <div class="left-side">
        <div class="company-info">
    <span>vex solutions</span>
        </div>
    <img src='<?php echo $this->getViewFileUrl('VexSolutions_LoginCustomization::images/vex1.jpg'); ?>' alt="image-icon" width="30" height="25">
</div>
    </div>
</div>
