<?php
/**
 *  * @author Eng.Asma Hawari
 *  * @package VexSolutions_LoginCustomization
 */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">

        <div class="logo">
            <span>Logo</span>
            <img src='<?php echo $this->getViewFileUrl('VexSolutions_LoginCustomization::images/vex.jpg'); ?>' alt="image-icon" width="30" height="25">
        </div>
    </div>
</div>
